### ISSUE TITLE
The bot is offline

### ISSUE THREAD

**Issue by YourCocoaCup** [igorquintaes/Discans#7]
I don't know how I'm supposed to wake it up since I used the command and it is effectively still dead

**Comment by igorquintaes** [comment]
Hello, @YourCocoaCup. Discans public bot is not more available. I also updated the documentation removing the previous link. You can still create and deploy your own Discans bot, using this repo code. Probably is needed to update `Discord.Net` package in order to fetch the updated Discord Api, since Discans was writtern years ago. I will update the lib and commit it soon here, if you still interested, but i don't think i am going to release a public bot again - due hosting costs and missing time to maintain it.
